# Generated by Django 5.0.6 on 2025-07-31 17:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoFertilizante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('fabricante', models.CharField(max_length=45)),
                ('linha', models.CharField(max_length=45)),
                ('forma_fisica', models.CharField(max_length=128)),
                ('finalidade', models.CharField(max_length=128)),
                ('nutrientes_primarios', models.CharField(max_length=128)),
                ('nutrientes_secundarios', models.CharField(max_length=128)),
                ('micronutrientes', models.CharField(max_length=128)),
                ('fonte_nutrientes', models.CharField(max_length=128)),
                ('data_cadastro', models.DateField(auto_now_add=True)),
                ('tipo_fertilizante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fertilizantes.tipofertilizante')),
            ],
        ),
    ]
