# Generated by Django 5.0.6 on 2025-08-03 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fertilizantes', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fertilizante',
        ),
        migrations.DeleteModel(
            name='TipoFertilizante',
        ),
    ]
