# Generated by Django 5.2.4 on 2025-08-04 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fazenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
                ('localizacao', models.CharField(max_length=255)),
                ('tamanho', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo_solo', models.CharField(max_length=100)),
                ('area', models.TextField()),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fazenda.fazenda')),
            ],
        ),
    ]
