# Generated by Django 5.2.4 on 2025-08-04 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fazenda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=100)),
                ('fabricante', models.CharField(blank=True, max_length=100, null=True)),
                ('formaFisica', models.CharField(blank=True, max_length=100, null=True)),
                ('finalidade', models.CharField(blank=True, max_length=100, null=True)),
                ('formulaComposicao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'insumo',
            },
        ),
        migrations.CreateModel(
            name='TipoAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_atividade',
            },
        ),
        migrations.CreateModel(
            name='TipoCoheita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_colheita',
            },
        ),
        migrations.CreateModel(
            name='Variedade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
            options={
                'db_table': 'variedade',
            },
        ),
        migrations.RemoveField(
            model_name='setor',
            name='tipo_solo',
        ),
        migrations.AddField(
            model_name='setor',
            name='dataPlantio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setor',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setor',
            name='espacamento',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='setor',
            name='tipoSolo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='setor',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterModelTable(
            name='fazenda',
            table='fazenda',
        ),
        migrations.AlterModelTable(
            name='setor',
            table='setor',
        ),
        migrations.CreateModel(
            name='Despesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fazenda.categoria')),
                ('fazenda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fazenda.fazenda')),
            ],
            options={
                'db_table': 'despesa',
            },
        ),
        migrations.CreateModel(
            name='AplicacaoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataAplicacao', models.DateField(blank=True, null=True)),
                ('dose', models.CharField(max_length=100)),
                ('unidade', models.CharField(max_length=50)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fazenda.setor')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fazenda.insumo')),
            ],
            options={
                'db_table': 'aplicacao_insumo',
            },
        ),
        migrations.CreateModel(
            name='Manejo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataInicio', models.DateField(blank=True, null=True)),
                ('dataFim', models.DateField(blank=True, null=True)),
                ('responsavel', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('custoMaterial', models.DecimalField(decimal_places=2, max_digits=6)),
                ('custoMaoObra', models.DecimalField(decimal_places=2, max_digits=6)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fazenda.setor')),
                ('tipoAtividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fazenda.tipoatividade')),
            ],
            options={
                'db_table': 'manejo',
            },
        ),
        migrations.CreateModel(
            name='Colheita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(blank=True, null=True)),
                ('peso', models.DecimalField(decimal_places=2, max_digits=6)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('valorTotal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fazenda.setor')),
                ('tipoColheita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fazenda.tipocoheita')),
                ('variedade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fazenda.variedade')),
            ],
            options={
                'db_table': 'colheita',
            },
        ),
        migrations.AddField(
            model_name='setor',
            name='variedades',
            field=models.ManyToManyField(blank=True, to='fazenda.variedade'),
        ),
    ]
