# Generated by Django 5.2.4 on 2025-08-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fazenda', '0002_categoria_insumo_tipoatividade_tipocoheita_variedade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cultura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
            ],
            options={
                'db_table': 'cultura',
            },
        ),
        migrations.AddField(
            model_name='colheita',
            name='ano',
            field=models.IntegerField(default=2025),
        ),
        migrations.AddField(
            model_name='setor',
            name='culturas',
            field=models.ManyToManyField(blank=True, to='fazenda.cultura'),
        ),
    ]
