# Generated by Django 5.2.4 on 2025-08-06 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fazenda', '0003_cultura_colheita_ano_setor_culturas'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_insumo',
            },
        ),
        migrations.AlterField(
            model_name='insumo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fazenda.tipoinsumo'),
        ),
    ]
