# Generated by Django 5.2.4 on 2025-08-06 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fazenda', '0004_tipoinsumo_alter_insumo_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='manejo',
            name='dose',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='manejo',
            name='insumo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='fazenda.insumo'),
        ),
        migrations.AddField(
            model_name='manejo',
            name='unidade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='manejo',
            name='dataInicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='manejo',
            name='descricao',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='manejo',
            name='responsavel',
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name='AplicacaoInsumo',
        ),
    ]
