# Generated by Django 5.2.4 on 2025-08-07 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fazenda', '0005_manejo_dose_manejo_insumo_manejo_unidade_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Setor',
            new_name='Quadra',
        ),
        migrations.RenameField(
            model_name='colheita',
            old_name='setor',
            new_name='quadra',
        ),
        migrations.RenameField(
            model_name='manejo',
            old_name='setor',
            new_name='quadra',
        ),
        migrations.AlterModelTable(
            name='quadra',
            table='quadra',
        ),
    ]
