# Generated by Django 5.2.4 on 2025-08-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fazenda', '0006_rename_setor_quadra_rename_setor_colheita_quadra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='aplicacao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
