# Generated by Django 5.2.4 on 2025-08-07 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fazenda', '0007_insumo_aplicacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fazenda',
            old_name='tamanho',
            new_name='area',
        ),
    ]
