# Generated by Django 5.2.4 on 2025-08-08 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fazenda', '0008_rename_tamanho_fazenda_area'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoCoheita',
            new_name='TipoColheita',
        ),
    ]
