# Generated by Django 5.2.4 on 2025-08-08 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fazenda', '0009_rename_tipocoheita_tipocolheita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='descricao',
            field=models.CharField(max_length=50),
        ),
    ]
