# Generated by Django 5.2.4 on 2025-08-15 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fazenda', '0010_alter_despesa_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesa',
            name='fazenda',
        ),
        migrations.RemoveField(
            model_name='quadra',
            name='fazenda',
        ),
        migrations.CreateModel(
            name='CalendarioAgricola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(choices=[('janeiro', 'Janeiro'), ('fevereiro', 'Fevereiro'), ('marco', 'Março'), ('abril', 'Abril'), ('maio', 'Maio'), ('junho', 'Junho'), ('julho', 'Julho'), ('agosto', 'Agosto'), ('setembro', 'Setembro'), ('outubro', 'Outubro'), ('novembro', 'Novembro'), ('dezembro', 'Dezembro')], max_length=20)),
                ('descricao', models.TextField()),
                ('atividades', models.TextField(help_text='Principais atividades do mês')),
                ('observacoes', models.TextField(blank=True, help_text='Observações adicionais', null=True)),
                ('cultura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fazenda.cultura')),
            ],
            options={
                'verbose_name': 'Calendário Agrícola',
                'verbose_name_plural': 'Calendários Agrícolas',
                'db_table': 'calendario_agricola',
                'unique_together': {('cultura', 'mes')},
            },
        ),
    ]
