# Generated by Django 5.2.4 on 2025-08-19 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fazenda', '0011_remove_despesa_fazenda_remove_quadra_fazenda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financiamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(help_text='Descrição do item financiado', max_length=200)),
                ('tipo', models.CharField(choices=[('maquina', 'Máquina'), ('equipamento', 'Equipamento'), ('veiculo', 'Veículo'), ('implemento', 'Implemento'), ('infraestrutura', 'Infraestrutura'), ('outros', 'Outros')], default='outros', max_length=20)),
                ('valor_total', models.DecimalField(decimal_places=2, help_text='Valor total do financiamento', max_digits=12)),
                ('valor_entrada', models.DecimalField(decimal_places=2, default=0, help_text='Valor da entrada', max_digits=12)),
                ('valor_financiado', models.DecimalField(decimal_places=2, help_text='Valor efetivamente financiado', max_digits=12)),
                ('instituicao_financeira', models.CharField(help_text='Banco ou instituição financeira', max_length=100)),
                ('taxa_juros', models.DecimalField(decimal_places=2, help_text='Taxa de juros mensal (%)', max_digits=5)),
                ('numero_parcelas', models.IntegerField(help_text='Número total de parcelas')),
                ('data_inicio', models.DateField(help_text='Data de início do financiamento')),
                ('data_vencimento_primeira', models.DateField(help_text='Data de vencimento da primeira parcela')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('quitado', 'Quitado'), ('em_atraso', 'Em Atraso'), ('cancelado', 'Cancelado')], default='ativo', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Financiamento',
                'verbose_name_plural': 'Financiamentos',
                'db_table': 'financiamento',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ParcelaFinanciamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.IntegerField(help_text='Número da parcela')),
                ('valor_parcela', models.DecimalField(decimal_places=2, help_text='Valor da parcela', max_digits=10)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, help_text='Valor efetivamente pago', max_digits=10)),
                ('data_vencimento', models.DateField(help_text='Data de vencimento da parcela')),
                ('data_pagamento', models.DateField(blank=True, help_text='Data do pagamento', null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('pago', 'Pago'), ('em_atraso', 'Em Atraso'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('juros_multa', models.DecimalField(decimal_places=2, default=0, help_text='Juros e multa por atraso', max_digits=8)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('financiamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fazenda.financiamento')),
            ],
            options={
                'verbose_name': 'Parcela de Financiamento',
                'verbose_name_plural': 'Parcelas de Financiamento',
                'db_table': 'parcela_financiamento',
                'ordering': ['financiamento', 'numero_parcela'],
                'unique_together': {('financiamento', 'numero_parcela')},
            },
        ),
    ]
