# Generated by Django 5.2.4 on 2025-08-19 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fazenda', '0012_financiamento_parcelafinanciamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financiamento',
            name='valor_entrada',
            field=models.CharField(help_text='Valor da entrada paga', max_length=20),
        ),
        migrations.AlterField(
            model_name='financiamento',
            name='valor_financiado',
            field=models.CharField(help_text='Valor efetivamente financiado', max_length=20),
        ),
        migrations.AlterField(
            model_name='financiamento',
            name='valor_total',
            field=models.CharField(help_text='Valor total do item/equipamento', max_length=20),
        ),
    ]
