# Generated by Django 5.2.4 on 2025-10-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fazenda', '0013_alter_financiamento_valor_entrada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='descricao',
            field=models.CharField(max_length=256),
        ),
    ]
