# Generated by Django 5.2.4 on 2025-10-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fazenda', '0014_alter_despesa_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='fonte',
            field=models.CharField(choices=[('RECURSOS_FAZENDA', 'Recursos da fazenda'), ('FINANCIAMENTO', 'Financiamento'), ('ARLEY_PINTO', 'Arley Pinto'), ('ALBERTH_COUTO', 'Alberth Couto'), ('LAURA_MARIA', 'Laura Maria')], default='RECURSOS_FAZENDA', max_length=20),
        ),
    ]
