# Generated by Django 5.0.6 on 2026-05-16 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fazenda', '0015_despesa_fonte'),
    ]

    operations = [
        migrations.AddField(
            model_name='colheita',
            name='cultura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fazenda.cultura'),
        ),
        migrations.AddField(
            model_name='colheita',
            name='situacao_vassoura_bruxa',
            field=models.CharField(blank=True, choices=[('', 'Nao se aplica'), ('COM', 'Cacau com vassoura de bruxa'), ('SEM', 'Cacau sem vassoura de bruxa')], default='', max_length=3),
        ),
    ]
