# Generated by Django 5.0.6 on 2026-05-16 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fazenda', '0016_colheita_cultura_colheita_situacao_vassoura_bruxa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colheita',
            name='preco',
        ),
        migrations.RemoveField(
            model_name='colheita',
            name='valorTotal',
        ),
        migrations.AddField(
            model_name='variedade',
            name='cultura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fazenda.cultura'),
        ),
    ]
