# Generated by Django 5.0.6 on 2026-05-18 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fazenda', '0018_preencher_cultura_variedades_existentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='quantidade_parcelas',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='despesa',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('parcial', 'Parcial'), ('paga', 'Paga')], default='aberta', max_length=10),
        ),
        migrations.CreateModel(
            name='PagamentoDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('numero_parcela', models.PositiveIntegerField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('despesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='fazenda.despesa')),
            ],
            options={
                'db_table': 'pagamento_despesa',
                'ordering': ['data_pagamento', 'numero_parcela', 'id'],
            },
        ),
    ]
