# Generated by Django 5.2.4 on 2026-05-18 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fazenda', '0019_despesa_quantidade_parcelas_despesa_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='data_primeiro_vencimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ParcelaDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.PositiveIntegerField()),
                ('data_vencimento', models.DateField()),
                ('valor_previsto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('parcial', 'Parcial'), ('paga', 'Paga')], default='aberta', max_length=10)),
                ('despesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='fazenda.despesa')),
            ],
            options={
                'db_table': 'parcela_despesa',
                'ordering': ['numero_parcela'],
                'unique_together': {('despesa', 'numero_parcela')},
            },
        ),
        migrations.AddField(
            model_name='pagamentodespesa',
            name='parcela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos', to='fazenda.parceladespesa'),
        ),
    ]
